# Generated by Django 5.1.1 on 2025-04-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopromocional',
            name='item',
        ),
        migrations.RemoveField(
            model_name='codigopromocional',
            name='usado',
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='saldo_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='usos_actuales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='usos_totales',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='usuario_ultimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='videojuego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lynx.videojuego'),
        ),
    ]
