# Generated by Django 5.1.9 on 2025-05-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0004_amistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistad',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada')], default='PENDIENTE', max_length=10),
        ),
    ]
