# Generated by Django 5.1.9 on 2025-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0005_amistad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopromocional',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
