# Generated by Django 5.1.9 on 2025-06-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0006_alter_codigopromocional_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='en_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
