# Generated by Django 5.1.9 on 2025-06-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0007_item_en_venta_item_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionitem',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
