# Generated by Django 5.1.9 on 2025-06-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0010_itemenventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='en_venta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='precio_venta',
        ),
    ]
